### ISSUE TITLE
Crash on dispose of image

### ISSUE THREAD

**Issue by NathanaelA** [mkloubert/nativescript-bitmap-factory#10]
Version: v1.7.0
Might be related to #1 as I am seeing this crash in the debugger in this same area of code.

The issue is in this code
https://github.com/mkloubert/nativescript-bitmap-factory/blob/master/plugin/BitmapFactory.ios.js#L59
```
var opts = this._options;
if (!TypeUtils.isNullOrUndefined(opts.ios)) {
```
There are several ways that you can get a iOSImage without  `this._options` defined.
So since opts = undefined, .ios of undefined = crash.

The solution is either:
`var opts = this._options || {};`
or
`if (opts && !TypeUtils.isNullOrUndefined(opts.ios)) {`

Since I wasn't sure which way you wanted it; I didn't create a pull request...  ;-)

**Comment by mkloubert** [comment]
Thanks! Fixed! :-)
