### ISSUE TITLE
is there way to load a image from a source then add text on it?

### ISSUE THREAD

**Issue by bori87** [mkloubert/nativescript-bitmap-factory#14]

**Comment by DanLatimer** [comment]
I was trying to find this to. Found this answer but it was closed with no info on how to do it. For anyone in the future looking for this functionality I believe it's the asBitmap function

https://github.com/mkloubert/nativescript-bitmap-factory/blob/83de658471728698de08e796cc6e99e8a6c21990/plugin/BitmapFactory.android.js#L403
