### ISSUE TITLE
Error: Actual arguments count: "1". Expected: "3" when using .resize

### ISSUE THREAD

**Issue by mlewis-everley** [mkloubert/nativescript-bitmap-factory#4]
I am getting this error when using ios 10.1.11, xcode 8.1 (though this should be an issue with older versions to) and nativescript 2.3.0

The issue appears to be at https://github.com/mkloubert/nativescript-bitmap-factory/blob/master/plugin/BitmapFactory.ios.js#L239

UIGraphicsBeginImageContextWithOptions is being called with only one argument (ns), but according to Apple's docs, it requires 3 arguments: https://developer.apple.com/reference/uikit/1623912-uigraphicsbeginimagecontextwitho?language=objc

My code is as follows:

````
        var image = ImageSource.fromFile(temp_path);
        var gcd = calculateGCD(width, height);
        var thumb_width = (((width / gcd) * 100) * 2);
        var thumb_height = (((height / gcd) * 100) * 2);

        // create a bitmap with original width and height
        var bmp = BitmapFactory.create(width, height);

        // Work with bitmap and make sure to free memory
        // after we do not need it anymore
        bmp.dispose(function(b) {
            b.insert(image.toBase64String(Enums.ImageFormat.jpeg, quality));

            var b2 = b.resize({
                width: thumb_width,
                height: thumb_height
            });

            var thumb_image = b2.toImageSource();

            thumb_image.saveToFile(
                temp_thumb_path,
                Enums.ImageFormat.jpeg
            );
        });
````

**Comment by mkloubert** [comment]
The bug should be fixed in version 1.3.1

**Comment by mlewis-everley** [comment]
Thanks for the prompt response Marcel, when is  1.3.1 due for release?

**Comment by mkloubert** [comment]
It should be available in [NPM package manager](https://www.npmjs.com/package/nativescript-bitmap-factory).

That means it is enough to reinstall the plugin by executing

```bash
tns plugin remove nativescript-bitmap-factory
tns plugin add nativescript-bitmap-factory
```

in your shell.

**Comment by mlewis-everley** [comment]
Ah ok, mine is running 1.2.2 currently, so will update and see if it works.

**Comment by mkloubert** [comment]
👍
