### ISSUE TITLE
have you thought about supporting rotation?

### ISSUE THREAD

**Issue by mlewis-everley** [mkloubert/nativescript-bitmap-factory#6]
Just a quick question/feature request.

As it currently stands, this is a great module for image creation or even basic photo manipulation, but having the ability to rotate images would be awesome.

Using android this can be done via matrix transforms, something like:

````    
            var image = ImageSource.fromFile(path);
            var new_image = new ImageSource.ImageSource();
            var quality = 100;
            var rotate = 90; // Rotate 90 degrees
            var matrix = new android.graphics.Matrix();
            matrix.postRotate(rotate);

            // Create new rotated bitmap using source image
            new_image.android = android.graphics.Bitmap.createBitmap(
                image.android,
                0,
                0,
                width,
                height,
                matrix,
                true
            );

            // Save new image to disk
            new_image.saveToFile(
                new_path,
                Enums.ImageFormat.jpeg,
                quality
            );
````

Performing similar on iOS however has proven difficult.

Just an idea, but if implemented would be a great tool to link to custom GUI's to perform basic image manipulation :-)

**Comment by mkloubert** [comment]
Yes. Is available in version 1.6.1 now ;-)

```typescript
let imgSrc = ImageSource.fromFile(path);
let originalBitmap = BitmapFactory.asBitmap(imgSrc);

// rotate +59.79 degrees
//
// is optional and +90 by default
let rotatedBitmap = originalBitmap.rotate(59.79);
```

**Comment by mlewis-everley** [comment]
Hmm, so I have tested this, but BitmapFactory.asBitmap(imgSrc) seems to return the good old "Immutable bitmap passed to Canvas constructor" exception.

I tested this using an instance of image source or as a native bitmap (generated using the makeMutable method) and got the same result. Any ideas?

**Comment by mkloubert** [comment]
Oh, the example is wrong.

You habe to use makeMutable() function.

**Comment by mlewis-everley** [comment]
Ok, it seems like my test phone was having some sort of moment earlier, I have tested rotation now and seems to work like a charm! :-)
